Running ant (compile)...................................................... OK
Running ant (compile.tests)................................................ OK
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:78)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.NullPointerException
	at org.joda.time.chrono.BasicChronology.getYearInfo(BasicChronology.java:414)
	at org.joda.time.chrono.BasicChronology.getYearMillis(BasicChronology.java:205)
	at org.joda.time.chrono.BasicChronology.getYear(BasicChronology.java:227)
	at org.joda.time.chrono.BasicMonthOfYearDateTimeField.set(BasicMonthOfYearDateTimeField.java:300)
	at org.joda.time.chrono.BaseChronology.set(BaseChronology.java:240)
	at org.joda.time.base.BaseSingleFieldPeriod.between(BaseSingleFieldPeriod.java:104)
	at org.joda.time.Days.daysBetween(Days.java:141)
	at org.joda.time.TestDays.testFactory_daysBetween_RPartial_MonthDay(TestDays.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:23)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:78)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
xxl.java.compiler.DynamicCompilationException: Aborting: dynamic compilation failed
	at xxl.java.compiler.DynamicClassCompiler.runCompilationTask(DynamicClassCompiler.java:88)
	at xxl.java.compiler.DynamicClassCompiler.javaBytecodeFor(DynamicClassCompiler.java:56)
	at fr.inria.lille.commons.spoon.SpoonedFile.compilationFor(SpoonedFile.java:177)
	at fr.inria.lille.commons.spoon.SpoonedFile.compileModelledClasses(SpoonedFile.java:154)
	at fr.inria.lille.commons.spoon.SpoonedFile.processModelledClasses(SpoonedFile.java:138)
	at fr.inria.lille.commons.spoon.SpoonedFile.process(SpoonedFile.java:128)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:119)
	at fr.inria.lille.commons.spoon.SpoonedFile.processedAndDumpedToClassLoader(SpoonedFile.java:115)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.<init>(ConstraintModelBuilder.java:57)
	at fr.inria.lille.repair.nopol.synth.SynthesizerFactory.getFor(SynthesizerFactory.java:122)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:164)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)

real	18m16.629s
user	32m43.804s
sys	0m8.880s
