Running ant (compile)...................................................... OK
Running ant (compile.tests)................................................ OK
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
## OAR [2017-11-27 23:03:41] Job 1442351 KILLED ##
com.sun.jdi.ClassNotPreparedException
	at com.sun.tools.jdi.JDWPException.toJDIException(JDWPException.java:51)
	at com.sun.tools.jdi.ReferenceTypeImpl.getInterfaces(ReferenceTypeImpl.java:572)
	at com.sun.tools.jdi.ClassTypeImpl.interfaces(ClassTypeImpl.java:70)
	at com.sun.tools.jdi.ClassTypeImpl.addVisibleMethods(ClassTypeImpl.java:392)
	at com.sun.tools.jdi.ReferenceTypeImpl.visibleMethods(ReferenceTypeImpl.java:526)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.getMethods(DataCollector.java:323)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectStaticMethods(DataCollector.java:303)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:118)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.sun.jdi.ClassNotPreparedException
	at com.sun.tools.jdi.JDWPException.toJDIException(JDWPException.java:51)
	at com.sun.tools.jdi.ReferenceTypeImpl.getInterfaces(ReferenceTypeImpl.java:572)
	at com.sun.tools.jdi.ClassTypeImpl.interfaces(ClassTypeImpl.java:70)
	at com.sun.tools.jdi.ClassTypeImpl.addVisibleMethods(ClassTypeImpl.java:392)
	at com.sun.tools.jdi.ReferenceTypeImpl.visibleMethods(ReferenceTypeImpl.java:526)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.getMethods(DataCollector.java:323)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectStaticMethods(DataCollector.java:303)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:118)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.sun.jdi.ClassNotPreparedException
	at com.sun.tools.jdi.JDWPException.toJDIException(JDWPException.java:51)
	at com.sun.tools.jdi.ReferenceTypeImpl.getInterfaces(ReferenceTypeImpl.java:572)
	at com.sun.tools.jdi.ClassTypeImpl.interfaces(ClassTypeImpl.java:70)
	at com.sun.tools.jdi.ClassTypeImpl.addVisibleMethods(ClassTypeImpl.java:392)
	at com.sun.tools.jdi.ReferenceTypeImpl.visibleMethods(ReferenceTypeImpl.java:526)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.getMethods(DataCollector.java:323)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectStaticMethods(DataCollector.java:303)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:118)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.joda.time.IllegalFieldValueException: Cannot parse "2000-02-29T00:00:00": Value 29 for dayOfMonth must be in the range [1,28]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:90)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:26)
	at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:59)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:229)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:264)
	at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:12)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:40)
	at org.joda.time.DateTime.<init>(DateTime.java:136)
	at org.joda.time.TestDateTimeComparator.getADate(TestDateTimeComparator.java:908)
	at org.joda.time.TestDateTimeComparator.testDOY(TestDateTimeComparator.java:514)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:27)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.joda.time.IllegalFieldValueException: Cannot parse "2000-02-29T00:00:00": Value 29 for dayOfMonth must be in the range [1,28]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:90)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:26)
	at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:59)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:229)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:264)
	at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:12)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:40)
	at org.joda.time.DateTime.<init>(DateTime.java:136)
	at org.joda.time.TestDateTimeComparator.getADate(TestDateTimeComparator.java:908)
	at org.joda.time.TestDateTimeComparator.testDOY(TestDateTimeComparator.java:514)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:27)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.joda.time.IllegalFieldValueException: Cannot parse "2000-02-29T00:00:00": Value 29 for dayOfMonth must be in the range [1,28]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:90)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:26)
	at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:59)
	at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:229)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:264)
	at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:12)
	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:40)
	at org.joda.time.DateTime.<init>(DateTime.java:136)
	at org.joda.time.TestDateTimeComparator.getADate(TestDateTimeComparator.java:908)
	at org.joda.time.TestDateTimeComparator.testDOY(TestDateTimeComparator.java:514)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:27)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-361542-thread-1" java.io.IOException: Resource not found: "org/joda/time/tz/data/UTC" ClassLoader: xxl.java.compiler.BytecodeClassLoader@3f6406ba
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:104)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:113)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:77)
	at org.joda.time.DateTimeZone.setProvider0(DateTimeZone.java:230)
	at org.joda.time.DateTimeZone.<clinit>(DateTimeZone.java:44)
	at org.joda.time.TestDateTimeZone.<clinit>(TestDateTimeZone.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:31)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:23)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-361904-thread-1" java.io.IOException: Resource not found: "org/joda/time/tz/data/UTC" ClassLoader: xxl.java.compiler.BytecodeClassLoader@66cc22ec
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:102)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:111)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:75)
	at org.joda.time.DateTimeZone.setProvider0(DateTimeZone.java:230)
	at org.joda.time.DateTimeZone.<clinit>(DateTimeZone.java:44)
	at org.joda.time.TestDateTimeZone.<clinit>(TestDateTimeZone.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:31)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:23)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-362267-thread-1" java.io.IOException: Resource not found: "org/joda/time/tz/data/UTC" ClassLoader: xxl.java.compiler.BytecodeClassLoader@8495d8a
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:102)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:111)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:75)
	at org.joda.time.DateTimeZone.setProvider0(DateTimeZone.java:230)
	at org.joda.time.DateTimeZone.<clinit>(DateTimeZone.java:44)
	at org.joda.time.TestDateTimeZone.<clinit>(TestDateTimeZone.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.SuiteMethod.testFromSuiteMethod(SuiteMethod.java:35)
	at org.junit.internal.runners.SuiteMethod.<init>(SuiteMethod.java:24)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:31)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:23)
	at xxl.java.junit.JUnitSingleTestRunner.call(JUnitSingleTestRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-366268-thread-1" java.io.IOException: Resource not found: "org/joda/time/tz/data/US/Central" ClassLoader: xxl.java.compiler.BytecodeClassLoader@33e41241
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:102)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:111)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:66)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:101)
	at org.joda.time.TestDateTimeZoneCutover.testBug2182444_usCentral(TestDateTimeZoneCutover.java:1176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:27)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-366371-thread-1" java.io.IOException: Resource not found: "org/joda/time/tz/data/Australia/NSW" ClassLoader: xxl.java.compiler.BytecodeClassLoader@33e41241
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:102)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:111)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:66)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:101)
	at org.joda.time.TestDateTimeZoneCutover.testBug2182444_ausNSW(TestDateTimeZoneCutover.java:1195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:27)
	at xxl.java.junit.JUnitSingleTestResultRunner.call(JUnitSingleTestResultRunner.java:10)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.sun.jdi.VMDisconnectedException: connection is closed
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:293)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1032)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$EventRequest$Set.enqueueCommand(JDWP.java:6763)
	at com.sun.tools.jdi.JDWP$EventRequest$Set.process(JDWP.java:6733)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.set(EventRequestManagerImpl.java:202)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.setEnabled(EventRequestManagerImpl.java:166)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.enableEventRequest(DataCollector.java:539)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethod(DataCollector.java:475)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethods(DataCollector.java:399)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectMethods(DataCollector.java:281)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectFieldAndMethodOnTheValueOf(DataCollector.java:154)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.recurse(DataCollector.java:138)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:121)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.sun.jdi.VMDisconnectedException: connection is closed
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:293)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1032)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$EventRequest$Clear.enqueueCommand(JDWP.java:6824)
	at com.sun.tools.jdi.JDWP$EventRequest$Clear.process(JDWP.java:6805)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.clear(EventRequestManagerImpl.java:212)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.setEnabled(EventRequestManagerImpl.java:164)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.disableEventRequest(DataCollector.java:530)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethod(DataCollector.java:416)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethods(DataCollector.java:399)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectMethods(DataCollector.java:281)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectFieldAndMethodOnTheValueOf(DataCollector.java:154)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.recurse(DataCollector.java:138)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:121)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
com.sun.jdi.VMDisconnectedException: connection is closed
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:293)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1032)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$EventRequest$Set.enqueueCommand(JDWP.java:6763)
	at com.sun.tools.jdi.JDWP$EventRequest$Set.process(JDWP.java:6733)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.set(EventRequestManagerImpl.java:202)
	at com.sun.tools.jdi.EventRequestManagerImpl$EventRequestImpl.setEnabled(EventRequestManagerImpl.java:166)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.enableEventRequest(DataCollector.java:539)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethod(DataCollector.java:475)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.callMethods(DataCollector.java:399)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectMethods(DataCollector.java:281)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collectFieldAndMethodOnTheValueOf(DataCollector.java:154)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.recurse(DataCollector.java:138)
	at fr.inria.lille.repair.synthesis.collect.DataCollector.collect(DataCollector.java:121)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.collectRuntimeValues(DynamothCodeGenesisImpl.java:388)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processBreakPointEvents(DynamothCodeGenesisImpl.java:290)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.processVMEvents(DynamothCodeGenesisImpl.java:187)
	at fr.inria.lille.repair.synthesis.DynamothCodeGenesisImpl.run(DynamothCodeGenesisImpl.java:156)
	at fr.inria.lille.repair.nopol.synth.dynamoth.DynamothSynthesizer.buildPatch(DynamothSynthesizer.java:150)
	at fr.inria.lille.repair.nopol.NoPol.runNopolProcessor(NoPol.java:287)
	at fr.inria.lille.repair.nopol.NoPol.access$000(NoPol.java:90)
	at fr.inria.lille.repair.nopol.NoPol$1.call(NoPol.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Command exited with non-zero status 255
11758.08user 6437.22system 2:04:37elapsed 243%CPU (0avgtext+0avgdata 4924988maxresident)k
105448inputs+331024outputs (44major+5692285minor)pagefaults 0swaps
